#!/usr/bin/env python3

from panflute import run_filter, stringify, Str, RawInline, Para


def action(elem, doc):
    if isinstance(elem, Str) and stringify(elem) == "lol" and isinstance(elem.parent, Para):
        elem = RawInline("\\ac{" + "lol" + "}", format="latex")
        return elem


def main(doc=None):
    main.test = "lol"
    return run_filter(action,
                      doc=doc)


if __name__ == '__main__':
    main()
